# Introduce yourself if you are learning or willing to help
# Blessings
print ("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
print ("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
print ("++                                                                    ++")
print ("++                                                                    ++")
print ("++                                                                    ++")
print ("++                 Welcome to this learning spot!                     ++")
print ("++                 Be possitive in your comments                      ++")
print ("++                            #BeLight                                ++")
print ("++                                                                    ++")
print ("++                                                                    ++")
print ("++                                                                    ++")
print ("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
print ("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
